### ISSUE TITLE
Inkorrekte Repository-URLs verhindern opkg-Nutzung

### ISSUE THREAD

**Issue by adlerweb** [FreifunkMYK/sites-ffmyk#4]
In den site.conf sin jeweils Verweise auf die internen Firmware-Mirror, z.B. https://github.com/FreifunkMYK/sites-ffmyk/blob/master/sites/ffmy/site.conf#L30 - diese URLs sind falsch. Bei `opkg update` führt dies entsprechend zu Fehlermeldungen und verhindert die Installation von Programmen, welche auf Kernel-Module angewiesen sind.

```
# opkg update
Downloading http://downloads.lede-project.org/releases/17.01-SNAPSHOT/packages/mips_24kc/base/Packages.gz
Updated list of available packages in /var/opkg-lists/reboot_base
Downloading http://downloads.lede-project.org/releases/17.01-SNAPSHOT/packages/mips_24kc/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/reboot_luci
Downloading http://downloads.lede-project.org/releases/17.01-SNAPSHOT/packages/mips_24kc/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/reboot_packages
Downloading http://downloads.lede-project.org/releases/17.01-SNAPSHOT/packages/mips_24kc/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/reboot_routing
Downloading http://downloads.lede-project.org/releases/17.01-SNAPSHOT/packages/mips_24kc/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/reboot_telephony
Downloading http://firmware.ffmy/packages/gluon-ffmy-0.5/ar71xx/generic/Packages.gz
*** Failed to download the package list from http://firmware.ffmy/packages/gluon-ffmy-0.5/ar71xx/generic/Packages.gz

Collected errors:
 * opkg_download: Failed to download http://firmware.ffmy/packages/gluon-ffmy-0.5/ar71xx/generic/Packages.gz, wget returned 4.
 * opkg_download: Check your network settings and connectivity.

```

**Comment by niyawe** [comment]
also aus dem koblenzer Netz klappt der download von `http://firmware.ffmy/packages/gluon-ffmy-0.5/ar71xx/generic/Packages.gz`. hast du das direkt nach einem Neustart des Routers probiert? Evtl kam das Router Advertisement da noch nicht an.

**Comment by adlerweb** [comment]
Nein, deutlich nach dem Neustart. MY-Netz. RA sollte da gewesen sein - lede-project.org war ja im selben Befehl erreichbar. Ich hatte auch mal die root per wget geladen, da gab es kein /packages. Stimmt denn die IP, die bei mir rausfällt? 2a03:2260:1016:1::1:2?

```
Downloading 'http://firmware.ffmy/'
Connecting to 2a03:2260:1016:1::1:2:80
Writing to stdout

<html>
        <head>
                <title>FFMYK-Firmware</title>
        </head>
        <body>
                <img src="/.static/logo.png" alt="Freifunk Mayen-Kobenz">
                <h1>Firmware-Download</h1>
                <hr>
                <a href="..">..</a><br>
                <a href="beta">Beta - Grundfunktion getestet, mehr Funktionen</a><br>
<a href="stable">Stable - Getestet & zuverlässig</a><br>

        </body>
</html>
-                    100% |*******************************|   349   0:00:00 ETA
Download completed (349 bytes)
```

Auch scheint hier wieder das Routing irgendwo quer zu hängen - ich hatte grade nochmal erfolgreich / per HTTP geladen und wollte /packages testen, da kam dann aber Timeout und ICMPv6 & co zur Ziel-IP gingen ins Leere während $Internet noch erreichbar war. Kurz drauf war er wieder für ein paar Sekunden da, scheint also sporadisch rauszufallen.

Die IP von firmware.ffmy ist auch von fastd-my2 und externen Hosts nicht erreichbar.
